import motorsPlusPlus as x
import utils as u
import constants as c
from wallaby import enable_servos, msleep
def init():
    enable_servos()
    u.move_servo(c.servoClaw, c.clawOpen, 100)
    u.move_servo(c.servoArm, c.armDown, 100)
    u.move_servo(c.servoCow,c.cowMid,100)
    msleep(300)

def goToBotAndCow():
    x.drive_speed(28, 100)
    x.rotate(87, 50)
    u.move_servo(c.servoArm, c.armBotguy, 10)
    x.drive_speed(16, 100)
    u.move_servo(c.servoArm, c.armDown, 10)
    msleep(300)
    u.move_servo(c.servoClaw, c.clawClose, 10)
    msleep(500)
    u.move_servo(c.servoArm, c.armUp, 10)
    x.drive_speed(7, -20)
    msleep(300)
    u.move_servo(c.servoArm, c.armUpBotguy, 10)
    msleep(300)
    u.move_servo(c.servoCow, c.cowUp, 10)
    msleep(300)
    x.drive_speed(7, -50)
    x.rotate(-90, 20)
    x.drive_speed(14, 50)
    x.rotate(180, 20)
    x.drive_speed(9, -50)
    u.move_servo(c.servoCowClaw, c.cowClawOpen, 10)
    msleep(500)
    u.move_servo(c.servoCow, c.cowDown, 10)
    msleep(1000)
    u.move_servo(c.servoCowClaw, c.cowClawClose, 10)
    msleep(500)
    u.move_servo(c.servoCow, c.cowUp,10)
    msleep(300)
    x.drive_speed(43, 100)
    x.rotate(30, 50)
    x.drive_speed(36, 100)
    x.drive_speed(6, -50)
    x.rotate(89, 50)
    x.drive_speed(30, 100)
    x.drive_speed(4, -50)
    x.rotate(79, 50)
    u.move_servo(c.servoArm, c.armBotguy,10)
    msleep(300)
    x.drive_speed(70, 75)
    u.move_servo(c.servoCow, c.cowDown, 10)
    msleep(300)
    x.rotate(-45, 50)